### PR TITLE
Add option to report added/deleted users

### PR DESCRIPTION
**Pull request by jordiclariana**

### CODE REVIEW

**Comment by rsanzante** [comment]
It seems that in README.md and default.yml the variable used is htpasswd_show_msg but in manage.yml the check is:

` when: htpasswd_list_users`

So I guess variable should be the same. I think htpasswd_list_users a better name.

**Comment by jordiclariana** [comment]
Definitely, that was a typo. I'll fix it. Thanks.

**Comment by jordiclariana** [comment]
Fixed!

**Comment by franklinkim** [comment]
thx

**Pull request merged**
